name: Publish docs

on:
  push:
    branches:
      - main

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Prep MkDocs
        run: .github/workflows/prepare_mkdocs.sh

      - name: Install plugins
        run: pip3 install mkdocs-material

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          SINGLE_COMMIT: true
