# Adapted from https://github.com/cashapp/sqldelight/blob/master/.github/workflows/gradle-wrapper-validation.yml

name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - main

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
